/** Generated by scripts/register-completion-atlases.py. */
export const COMPLETION_SHEETS = [
  {
    "key": "generated-business-decor",
    "file": "business-decor"
  },
  {
    "key": "generated-world-details",
    "file": "world-details"
  },
  {
    "key": "generated-stations-premium",
    "file": "stations-premium"
  }
] as const;
export const COMPLETION_FRAMES = {
  "decor_dropship_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 8,
    "y": 15,
    "w": 229,
    "h": 220,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_restaurant_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 250,
    "y": 3,
    "w": 222,
    "h": 234,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_tiktok_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 487,
    "y": 18,
    "w": 218,
    "h": 219,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_ai_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 719,
    "y": 11,
    "w": 216,
    "h": 226,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_foodtruck_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 949,
    "y": 17,
    "w": 235,
    "h": 220,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_beachclub_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1192,
    "y": 3,
    "w": 219,
    "h": 234,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_yachts_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1427,
    "y": 30,
    "w": 217,
    "h": 207,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_realestate_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 6,
    "y": 243,
    "w": 231,
    "h": 228,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_crypto_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 253,
    "y": 237,
    "w": 215,
    "h": 228,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_supercars_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 474,
    "y": 256,
    "w": 237,
    "h": 215,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_hotel_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 714,
    "y": 237,
    "w": 234,
    "h": 227,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_safari_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 959,
    "y": 237,
    "w": 226,
    "h": 233,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_souk_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1197,
    "y": 237,
    "w": 225,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_tower_2": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1434,
    "y": 237,
    "w": 225,
    "h": 236,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_dropship_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 5,
    "y": 474,
    "w": 232,
    "h": 231,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_restaurant_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 250,
    "y": 474,
    "w": 224,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_tiktok_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 480,
    "y": 489,
    "w": 231,
    "h": 222,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_ai_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 717,
    "y": 474,
    "w": 231,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_foodtruck_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 954,
    "y": 474,
    "w": 231,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_beachclub_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1191,
    "y": 474,
    "w": 231,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_yachts_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1425,
    "y": 474,
    "w": 232,
    "h": 237,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_realestate_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 2,
    "y": 711,
    "w": 235,
    "h": 224,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_crypto_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 237,
    "y": 711,
    "w": 237,
    "h": 229,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_supercars_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 474,
    "y": 711,
    "w": 237,
    "h": 233,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_hotel_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 711,
    "y": 711,
    "w": 237,
    "h": 227,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_safari_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 948,
    "y": 711,
    "w": 237,
    "h": 234,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_souk_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1185,
    "y": 711,
    "w": 237,
    "h": 234,
    "sheetW": 1659,
    "sheetH": 948
  },
  "decor_tower_3": {
    "sheet": "generated-business-decor",
    "file": "business-decor",
    "x": 1422,
    "y": 711,
    "w": 237,
    "h": 228,
    "sheetW": 1659,
    "sheetH": 948
  },
  "veh_order": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 32,
    "y": 20,
    "w": 352,
    "h": 296,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "ch_critic_0": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 467,
    "y": 10,
    "w": 288,
    "h": 305,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "prop_broadcast": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 809,
    "y": 10,
    "w": 343,
    "h": 305,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "prop_research": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 1238,
    "y": 23,
    "w": 250,
    "h": 293,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tree_0": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 49,
    "y": 316,
    "w": 324,
    "h": 299,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tree_1": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 493,
    "y": 316,
    "w": 215,
    "h": 299,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "palm": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 819,
    "y": 316,
    "w": 306,
    "h": 297,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bush": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 1186,
    "y": 377,
    "w": 314,
    "h": 217,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bench": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 69,
    "y": 632,
    "w": 271,
    "h": 209,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lamp_post": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 561,
    "y": 615,
    "w": 78,
    "h": 226,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "recycling_bin": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 902,
    "y": 630,
    "w": 153,
    "h": 211,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "desert_palm": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 1204,
    "y": 615,
    "w": 295,
    "h": 226,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tile_madrid_ground": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 14,
    "y": 841,
    "w": 370,
    "h": 173,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tile_miami_ground": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 395,
    "y": 841,
    "w": 373,
    "h": 176,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tile_dubai_ground": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 777,
    "y": 841,
    "w": 370,
    "h": 175,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "tile_path": {
    "sheet": "generated-world-details",
    "file": "world-details",
    "x": 1152,
    "y": 841,
    "w": 375,
    "h": 176,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "st_dropship_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 3,
    "y": 78,
    "w": 209,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_restaurant_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 212,
    "y": 65,
    "w": 211,
    "h": 254,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_tiktok_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 423,
    "y": 90,
    "w": 212,
    "h": 235,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_ai_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 649,
    "y": 91,
    "w": 198,
    "h": 223,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_foodtruck_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 847,
    "y": 89,
    "w": 212,
    "h": 222,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_beachclub_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1059,
    "y": 72,
    "w": 211,
    "h": 246,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_yachts_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1270,
    "y": 94,
    "w": 210,
    "h": 231,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_realestate_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 3,
    "y": 343,
    "w": 209,
    "h": 218,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_crypto_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 218,
    "y": 352,
    "w": 195,
    "h": 195,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_supercars_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 423,
    "y": 325,
    "w": 212,
    "h": 238,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_hotel_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 635,
    "y": 337,
    "w": 212,
    "h": 229,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_safari_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 847,
    "y": 333,
    "w": 212,
    "h": 225,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_souk_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1059,
    "y": 339,
    "w": 211,
    "h": 222,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_tower_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1270,
    "y": 325,
    "w": 206,
    "h": 241,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_dropship_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 7,
    "y": 566,
    "w": 205,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_restaurant_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 212,
    "y": 566,
    "w": 211,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_tiktok_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 423,
    "y": 574,
    "w": 212,
    "h": 231,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_ai_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 646,
    "y": 566,
    "w": 201,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_foodtruck_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 847,
    "y": 588,
    "w": 212,
    "h": 216,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_beachclub_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1059,
    "y": 566,
    "w": 211,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_yachts_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1270,
    "y": 566,
    "w": 212,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_realestate_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 5,
    "y": 810,
    "w": 207,
    "h": 237,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_crypto_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 212,
    "y": 835,
    "w": 204,
    "h": 201,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_supercars_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 423,
    "y": 808,
    "w": 212,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_hotel_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 635,
    "y": 807,
    "w": 212,
    "h": 243,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_safari_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 847,
    "y": 805,
    "w": 212,
    "h": 246,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_souk_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1059,
    "y": 827,
    "w": 211,
    "h": 219,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "st_tower_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 1270,
    "y": 805,
    "w": 210,
    "h": 253,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "wh_shelf_r4": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 3,
    "y": 78,
    "w": 209,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  },
  "wh_shelf_r5": {
    "sheet": "generated-stations-premium",
    "file": "stations-premium",
    "x": 7,
    "y": 566,
    "w": 205,
    "h": 239,
    "sheetW": 1482,
    "sheetH": 1061
  }
};
