/** Generated by scripts/export-world-routes.mjs. */
export const ROUTE_SIZES: Record<string,{w:number;h:number}> = {
  "band_dropship": {
    "w": 390,
    "h": 172
  },
  "route_dropship_h": {
    "w": 60,
    "h": 30
  },
  "route_dropship_v": {
    "w": 30,
    "h": 60
  },
  "route_dropship_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_dropship_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_dropship_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_dropship_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_dropship_stop": {
    "w": 60,
    "h": 40
  },
  "route_dropship_ghost": {
    "w": 60,
    "h": 30
  },
  "route_dropship_works": {
    "w": 60,
    "h": 44
  },
  "band_restaurant": {
    "w": 390,
    "h": 172
  },
  "route_restaurant_h": {
    "w": 60,
    "h": 30
  },
  "route_restaurant_v": {
    "w": 30,
    "h": 60
  },
  "route_restaurant_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_restaurant_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_restaurant_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_restaurant_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_restaurant_stop": {
    "w": 60,
    "h": 40
  },
  "route_restaurant_ghost": {
    "w": 60,
    "h": 30
  },
  "route_restaurant_works": {
    "w": 60,
    "h": 44
  },
  "band_tiktok": {
    "w": 390,
    "h": 172
  },
  "route_tiktok_h": {
    "w": 60,
    "h": 30
  },
  "route_tiktok_v": {
    "w": 30,
    "h": 60
  },
  "route_tiktok_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_tiktok_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_tiktok_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_tiktok_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_tiktok_stop": {
    "w": 60,
    "h": 40
  },
  "route_tiktok_ghost": {
    "w": 60,
    "h": 30
  },
  "route_tiktok_works": {
    "w": 60,
    "h": 44
  },
  "band_ai": {
    "w": 390,
    "h": 172
  },
  "route_ai_h": {
    "w": 60,
    "h": 30
  },
  "route_ai_v": {
    "w": 30,
    "h": 60
  },
  "route_ai_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_ai_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_ai_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_ai_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_ai_stop": {
    "w": 60,
    "h": 40
  },
  "route_ai_ghost": {
    "w": 60,
    "h": 30
  },
  "route_ai_works": {
    "w": 60,
    "h": 44
  },
  "band_foodtruck": {
    "w": 390,
    "h": 172
  },
  "route_foodtruck_h": {
    "w": 60,
    "h": 30
  },
  "route_foodtruck_v": {
    "w": 30,
    "h": 60
  },
  "route_foodtruck_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_foodtruck_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_foodtruck_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_foodtruck_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_foodtruck_stop": {
    "w": 60,
    "h": 40
  },
  "route_foodtruck_ghost": {
    "w": 60,
    "h": 30
  },
  "route_foodtruck_works": {
    "w": 60,
    "h": 44
  },
  "band_beachclub": {
    "w": 390,
    "h": 172
  },
  "route_beachclub_h": {
    "w": 60,
    "h": 30
  },
  "route_beachclub_v": {
    "w": 30,
    "h": 60
  },
  "route_beachclub_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_beachclub_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_beachclub_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_beachclub_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_beachclub_stop": {
    "w": 60,
    "h": 40
  },
  "route_beachclub_ghost": {
    "w": 60,
    "h": 30
  },
  "route_beachclub_works": {
    "w": 60,
    "h": 44
  },
  "band_yachts": {
    "w": 390,
    "h": 172
  },
  "route_yachts_h": {
    "w": 60,
    "h": 30
  },
  "route_yachts_v": {
    "w": 30,
    "h": 60
  },
  "route_yachts_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_yachts_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_yachts_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_yachts_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_yachts_stop": {
    "w": 60,
    "h": 40
  },
  "route_yachts_ghost": {
    "w": 60,
    "h": 30
  },
  "route_yachts_works": {
    "w": 60,
    "h": 44
  },
  "band_realestate": {
    "w": 390,
    "h": 172
  },
  "route_realestate_h": {
    "w": 60,
    "h": 30
  },
  "route_realestate_v": {
    "w": 30,
    "h": 60
  },
  "route_realestate_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_realestate_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_realestate_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_realestate_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_realestate_stop": {
    "w": 60,
    "h": 40
  },
  "route_realestate_ghost": {
    "w": 60,
    "h": 30
  },
  "route_realestate_works": {
    "w": 60,
    "h": 44
  },
  "band_crypto": {
    "w": 390,
    "h": 172
  },
  "route_crypto_h": {
    "w": 60,
    "h": 30
  },
  "route_crypto_v": {
    "w": 30,
    "h": 60
  },
  "route_crypto_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_crypto_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_crypto_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_crypto_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_crypto_stop": {
    "w": 60,
    "h": 40
  },
  "route_crypto_ghost": {
    "w": 60,
    "h": 30
  },
  "route_crypto_works": {
    "w": 60,
    "h": 44
  },
  "band_supercars": {
    "w": 390,
    "h": 172
  },
  "route_supercars_h": {
    "w": 60,
    "h": 30
  },
  "route_supercars_v": {
    "w": 30,
    "h": 60
  },
  "route_supercars_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_supercars_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_supercars_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_supercars_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_supercars_stop": {
    "w": 60,
    "h": 40
  },
  "route_supercars_ghost": {
    "w": 60,
    "h": 30
  },
  "route_supercars_works": {
    "w": 60,
    "h": 44
  },
  "band_hotel": {
    "w": 390,
    "h": 172
  },
  "route_hotel_h": {
    "w": 60,
    "h": 30
  },
  "route_hotel_v": {
    "w": 30,
    "h": 60
  },
  "route_hotel_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_hotel_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_hotel_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_hotel_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_hotel_stop": {
    "w": 60,
    "h": 40
  },
  "route_hotel_ghost": {
    "w": 60,
    "h": 30
  },
  "route_hotel_works": {
    "w": 60,
    "h": 44
  },
  "band_safari": {
    "w": 390,
    "h": 172
  },
  "route_safari_h": {
    "w": 60,
    "h": 30
  },
  "route_safari_v": {
    "w": 30,
    "h": 60
  },
  "route_safari_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_safari_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_safari_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_safari_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_safari_stop": {
    "w": 60,
    "h": 40
  },
  "route_safari_ghost": {
    "w": 60,
    "h": 30
  },
  "route_safari_works": {
    "w": 60,
    "h": 44
  },
  "band_souk": {
    "w": 390,
    "h": 172
  },
  "route_souk_h": {
    "w": 60,
    "h": 30
  },
  "route_souk_v": {
    "w": 30,
    "h": 60
  },
  "route_souk_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_souk_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_souk_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_souk_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_souk_stop": {
    "w": 60,
    "h": 40
  },
  "route_souk_ghost": {
    "w": 60,
    "h": 30
  },
  "route_souk_works": {
    "w": 60,
    "h": 44
  },
  "band_tower": {
    "w": 390,
    "h": 172
  },
  "route_tower_h": {
    "w": 60,
    "h": 30
  },
  "route_tower_v": {
    "w": 30,
    "h": 60
  },
  "route_tower_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_tower_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_tower_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_tower_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_tower_stop": {
    "w": 60,
    "h": 40
  },
  "route_tower_ghost": {
    "w": 60,
    "h": 30
  },
  "route_tower_works": {
    "w": 60,
    "h": 44
  },
  "band_fest": {
    "w": 390,
    "h": 172
  },
  "route_fest_h": {
    "w": 60,
    "h": 30
  },
  "route_fest_v": {
    "w": 30,
    "h": 60
  },
  "route_fest_turn_ne": {
    "w": 48,
    "h": 48
  },
  "route_fest_turn_nw": {
    "w": 48,
    "h": 48
  },
  "route_fest_turn_se": {
    "w": 48,
    "h": 48
  },
  "route_fest_turn_sw": {
    "w": 48,
    "h": 48
  },
  "route_fest_stop": {
    "w": 60,
    "h": 40
  },
  "route_fest_ghost": {
    "w": 60,
    "h": 30
  },
  "route_fest_works": {
    "w": 60,
    "h": 44
  }
};
