/** Original visual completion atlases. Generated by scripts/register-visual-atlases.py. */
export const VISUAL_SHEETS = [
  {
    "key": "generated-vehicles",
    "file": "vehicles"
  },
  {
    "key": "generated-dubai-buildings",
    "file": "dubai-buildings"
  },
  {
    "key": "generated-avatars",
    "file": "avatars"
  },
  {
    "key": "generated-dubai-details",
    "file": "dubai-details"
  },
  {
    "key": "generated-luxury",
    "file": "luxury"
  },
  {
    "key": "generated-lifestyle-extras",
    "file": "lifestyle-extras"
  }
] as const;
export const VISUAL_FRAMES: Record<string, { sheet: string; file: string; x: number; y: number; w: number; h: number; sheetW: number; sheetH: number }> = {
  "veh_safari": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 27,
    "y": 61,
    "w": 416,
    "h": 381,
    "sheetW": 1774,
    "sheetH": 887
  },
  "veh_crane": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 450,
    "y": 53,
    "w": 433,
    "h": 383,
    "sheetW": 1774,
    "sheetH": 887
  },
  "veh_luggage": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 909,
    "y": 90,
    "w": 412,
    "h": 353,
    "sheetW": 1774,
    "sheetH": 887
  },
  "veh_flatbed": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 1330,
    "y": 99,
    "w": 426,
    "h": 332,
    "sheetW": 1774,
    "sheetH": 887
  },
  "veh_goldvan": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 24,
    "y": 467,
    "w": 420,
    "h": 369,
    "sheetW": 1774,
    "sheetH": 887
  },
  "car_miami_0": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 448,
    "y": 520,
    "w": 438,
    "h": 311,
    "sheetW": 1774,
    "sheetH": 887
  },
  "car_miami_1": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 889,
    "y": 521,
    "w": 441,
    "h": 312,
    "sheetW": 1774,
    "sheetH": 887
  },
  "dubai_lamp": {
    "sheet": "generated-vehicles",
    "file": "vehicles",
    "x": 1422,
    "y": 443,
    "w": 243,
    "h": 401,
    "sheetW": 1774,
    "sheetH": 887
  },
  "bld_supercars_1": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 9,
    "y": 103,
    "w": 298,
    "h": 209,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_hotel_1": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 355,
    "y": 4,
    "w": 259,
    "h": 308,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_safari_1": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 653,
    "y": 101,
    "w": 269,
    "h": 211,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_souk_1": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 982,
    "y": 87,
    "w": 247,
    "h": 225,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_tower_1": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 1318,
    "y": 4,
    "w": 195,
    "h": 300,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_supercars_2": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 3,
    "y": 425,
    "w": 304,
    "h": 226,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_hotel_2": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 324,
    "y": 312,
    "w": 290,
    "h": 336,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_safari_2": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 650,
    "y": 402,
    "w": 272,
    "h": 253,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_souk_2": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 983,
    "y": 384,
    "w": 246,
    "h": 266,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_tower_2": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 1309,
    "y": 312,
    "w": 222,
    "h": 334,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_supercars_3": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 0,
    "y": 707,
    "w": 307,
    "h": 294,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_hotel_3": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 307,
    "y": 655,
    "w": 307,
    "h": 353,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_safari_3": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 614,
    "y": 712,
    "w": 308,
    "h": 297,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_souk_3": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 922,
    "y": 702,
    "w": 307,
    "h": 296,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "bld_tower_3": {
    "sheet": "generated-dubai-buildings",
    "file": "dubai-buildings",
    "x": 1229,
    "y": 655,
    "w": 306,
    "h": 343,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_tracksuit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 22,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_hoodie": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 406,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_suit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 790,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_designer": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 1174,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_goldtux": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 22,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_neonsuit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 406,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_vampire": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 790,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "avatar_founder": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 1174,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_tracksuit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 22,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_hoodie": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 406,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_suit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 790,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_designer": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 1174,
    "y": 4,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_goldtux": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 22,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_neonsuit": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 406,
    "y": 516,
    "w": 340,
    "h": 504,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "exec_founder": {
    "sheet": "generated-avatars",
    "file": "avatars",
    "x": 1174,
    "y": 516,
    "w": 340,
    "h": 237,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "st_supercars": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 33,
    "y": 7,
    "w": 338,
    "h": 280,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "st_hotel": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 392,
    "y": 3,
    "w": 337,
    "h": 292,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "st_safari": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 734,
    "y": 1,
    "w": 382,
    "h": 292,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "st_souk": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 1122,
    "y": 10,
    "w": 295,
    "h": 285,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "st_tower": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 32,
    "y": 295,
    "w": 342,
    "h": 270,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "item_carkey": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 458,
    "y": 321,
    "w": 219,
    "h": 225,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "item_bell": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 786,
    "y": 320,
    "w": 263,
    "h": 219,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "item_camel": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 1141,
    "y": 296,
    "w": 251,
    "h": 269,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "item_ring": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 103,
    "y": 577,
    "w": 190,
    "h": 231,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "item_beam": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 453,
    "y": 570,
    "w": 259,
    "h": 214,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_mechanic_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 832,
    "y": 565,
    "w": 159,
    "h": 243,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_valet_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 1208,
    "y": 565,
    "w": 117,
    "h": 243,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_butler_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 111,
    "y": 808,
    "w": 127,
    "h": 277,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_guide_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 481,
    "y": 808,
    "w": 167,
    "h": 275,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_goldsmith_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 830,
    "y": 808,
    "w": 172,
    "h": 276,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "ch_builder_0": {
    "sheet": "generated-dubai-details",
    "file": "dubai-details",
    "x": 1174,
    "y": 808,
    "w": 161,
    "h": 277,
    "sheetW": 1448,
    "sheetH": 1086
  },
  "lux_digital": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 44,
    "y": 27,
    "w": 208,
    "h": 236,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_luxwatch": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 334,
    "y": 21,
    "w": 196,
    "h": 246,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_goldchain": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 619,
    "y": 41,
    "w": 299,
    "h": 211,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_diamondring": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1002,
    "y": 35,
    "w": 183,
    "h": 226,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_crown": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1276,
    "y": 21,
    "w": 240,
    "h": 246,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_deliverybike": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 44,
    "y": 277,
    "w": 234,
    "h": 236,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_scooter": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 344,
    "y": 282,
    "w": 205,
    "h": 224,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_motorbike": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 625,
    "y": 294,
    "w": 275,
    "h": 209,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_sportscar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 929,
    "y": 319,
    "w": 298,
    "h": 170,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_supercar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1242,
    "y": 302,
    "w": 279,
    "h": 192,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_limo": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 10,
    "y": 548,
    "w": 297,
    "h": 175,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_goldcar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 313,
    "y": 557,
    "w": 284,
    "h": 162,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_parents": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 614,
    "y": 516,
    "w": 308,
    "h": 235,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_flat": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 941,
    "y": 515,
    "w": 288,
    "h": 237,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_penthouse": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1245,
    "y": 515,
    "w": 283,
    "h": 239,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_villa": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 12,
    "y": 754,
    "w": 295,
    "h": 246,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_mansion": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 313,
    "y": 756,
    "w": 301,
    "h": 229,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_island": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 621,
    "y": 759,
    "w": 301,
    "h": 233,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_hearse": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 926,
    "y": 789,
    "w": 303,
    "h": 177,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_haunted": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1247,
    "y": 754,
    "w": 281,
    "h": 244,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_deliverybike": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 44,
    "y": 277,
    "w": 234,
    "h": 236,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_scooter": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 344,
    "y": 282,
    "w": 205,
    "h": 224,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_motorbike": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 625,
    "y": 294,
    "w": 275,
    "h": 209,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_sportscar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 929,
    "y": 319,
    "w": 298,
    "h": 170,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_supercar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 1242,
    "y": 302,
    "w": 279,
    "h": 192,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_limo": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 10,
    "y": 548,
    "w": 297,
    "h": 175,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_goldcar": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 313,
    "y": 557,
    "w": 284,
    "h": 162,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "luxcar_hearse": {
    "sheet": "generated-luxury",
    "file": "luxury",
    "x": 926,
    "y": 789,
    "w": 303,
    "h": 177,
    "sheetW": 1536,
    "sheetH": 1024
  },
  "lux_cat": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 29,
    "y": 0,
    "w": 274,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_dog": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 336,
    "y": 0,
    "w": 282,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_parrot": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 675,
    "y": 0,
    "w": 232,
    "h": 315,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_tiger": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 971,
    "y": 1,
    "w": 257,
    "h": 314,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_penguin": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 0,
    "y": 315,
    "w": 314,
    "h": 311,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_pumpkin": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 322,
    "y": 333,
    "w": 295,
    "h": 284,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_yacht": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 627,
    "y": 342,
    "w": 313,
    "h": 254,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_jet": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 940,
    "y": 351,
    "w": 314,
    "h": 259,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_rocket": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 16,
    "y": 626,
    "w": 255,
    "h": 309,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_vampire": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 314,
    "y": 626,
    "w": 313,
    "h": 292,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "lux_skullring": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 647,
    "y": 654,
    "w": 293,
    "h": 252,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "ghost": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 950,
    "y": 631,
    "w": 291,
    "h": 291,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "veh_supply": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 10,
    "y": 935,
    "w": 304,
    "h": 305,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "ch_vip_0": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 376,
    "y": 935,
    "w": 198,
    "h": 319,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "dubai_planter": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "miami_plaza": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "pumpkin": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 322,
    "y": 333,
    "w": 295,
    "h": 284,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_supercars_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_supercars_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_hotel_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_hotel_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_safari_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_safari_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_souk_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_souk_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_tower_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_tower_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 660,
    "y": 935,
    "w": 262,
    "h": 313,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_foodtruck_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_foodtruck_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_beachclub_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_beachclub_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_yachts_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_yachts_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_realestate_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_realestate_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_crypto_2": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  },
  "decor_crypto_3": {
    "sheet": "generated-lifestyle-extras",
    "file": "lifestyle-extras",
    "x": 945,
    "y": 935,
    "w": 294,
    "h": 312,
    "sheetW": 1254,
    "sheetH": 1254
  }
};
