/** Generated by scripts/export-world-art.mjs; originals remain versioned. */
export const WORLD_SIZES: Record<string,{w:number;h:number}> = {
  "st_dropship_0": {
    "w": 104,
    "h": 80
  },
  "st_dropship_1": {
    "w": 104,
    "h": 80
  },
  "st_dropship_2": {
    "w": 104,
    "h": 80
  },
  "st_dropship_3": {
    "w": 104,
    "h": 80
  },
  "st_dropship_4": {
    "w": 104,
    "h": 80
  },
  "st_dropship_5": {
    "w": 104,
    "h": 80
  },
  "st_dropship_6": {
    "w": 104,
    "h": 80
  },
  "st_dropship_7": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_0": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_1": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_2": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_3": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_4": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_5": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_6": {
    "w": 104,
    "h": 80
  },
  "st_restaurant_7": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_0": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_1": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_2": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_3": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_4": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_5": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_6": {
    "w": 104,
    "h": 80
  },
  "st_tiktok_7": {
    "w": 104,
    "h": 80
  },
  "st_ai_0": {
    "w": 104,
    "h": 80
  },
  "st_ai_1": {
    "w": 104,
    "h": 80
  },
  "st_ai_2": {
    "w": 104,
    "h": 80
  },
  "st_ai_3": {
    "w": 104,
    "h": 80
  },
  "st_ai_4": {
    "w": 104,
    "h": 80
  },
  "st_ai_5": {
    "w": 104,
    "h": 80
  },
  "st_ai_6": {
    "w": 104,
    "h": 80
  },
  "st_ai_7": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_0": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_1": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_2": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_3": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_4": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_5": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_6": {
    "w": 104,
    "h": 80
  },
  "st_foodtruck_7": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_0": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_1": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_2": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_3": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_4": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_5": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_6": {
    "w": 104,
    "h": 80
  },
  "st_beachclub_7": {
    "w": 104,
    "h": 80
  },
  "st_yachts_0": {
    "w": 104,
    "h": 80
  },
  "st_yachts_1": {
    "w": 104,
    "h": 80
  },
  "st_yachts_2": {
    "w": 104,
    "h": 80
  },
  "st_yachts_3": {
    "w": 104,
    "h": 80
  },
  "st_yachts_4": {
    "w": 104,
    "h": 80
  },
  "st_yachts_5": {
    "w": 104,
    "h": 80
  },
  "st_yachts_6": {
    "w": 104,
    "h": 80
  },
  "st_yachts_7": {
    "w": 104,
    "h": 80
  },
  "st_realestate_0": {
    "w": 104,
    "h": 80
  },
  "st_realestate_1": {
    "w": 104,
    "h": 80
  },
  "st_realestate_2": {
    "w": 104,
    "h": 80
  },
  "st_realestate_3": {
    "w": 104,
    "h": 80
  },
  "st_realestate_4": {
    "w": 104,
    "h": 80
  },
  "st_realestate_5": {
    "w": 104,
    "h": 80
  },
  "st_realestate_6": {
    "w": 104,
    "h": 80
  },
  "st_realestate_7": {
    "w": 104,
    "h": 80
  },
  "st_crypto_0": {
    "w": 104,
    "h": 80
  },
  "st_crypto_1": {
    "w": 104,
    "h": 80
  },
  "st_crypto_2": {
    "w": 104,
    "h": 80
  },
  "st_crypto_3": {
    "w": 104,
    "h": 80
  },
  "st_crypto_4": {
    "w": 104,
    "h": 80
  },
  "st_crypto_5": {
    "w": 104,
    "h": 80
  },
  "st_crypto_6": {
    "w": 104,
    "h": 80
  },
  "st_crypto_7": {
    "w": 104,
    "h": 80
  },
  "st_supercars_0": {
    "w": 104,
    "h": 80
  },
  "st_supercars_1": {
    "w": 104,
    "h": 80
  },
  "st_supercars_2": {
    "w": 104,
    "h": 80
  },
  "st_supercars_3": {
    "w": 104,
    "h": 80
  },
  "st_supercars_4": {
    "w": 104,
    "h": 80
  },
  "st_supercars_5": {
    "w": 104,
    "h": 80
  },
  "st_supercars_6": {
    "w": 104,
    "h": 80
  },
  "st_supercars_7": {
    "w": 104,
    "h": 80
  },
  "st_hotel_0": {
    "w": 104,
    "h": 80
  },
  "st_hotel_1": {
    "w": 104,
    "h": 80
  },
  "st_hotel_2": {
    "w": 104,
    "h": 80
  },
  "st_hotel_3": {
    "w": 104,
    "h": 80
  },
  "st_hotel_4": {
    "w": 104,
    "h": 80
  },
  "st_hotel_5": {
    "w": 104,
    "h": 80
  },
  "st_hotel_6": {
    "w": 104,
    "h": 80
  },
  "st_hotel_7": {
    "w": 104,
    "h": 80
  },
  "st_safari_0": {
    "w": 104,
    "h": 80
  },
  "st_safari_1": {
    "w": 104,
    "h": 80
  },
  "st_safari_2": {
    "w": 104,
    "h": 80
  },
  "st_safari_3": {
    "w": 104,
    "h": 80
  },
  "st_safari_4": {
    "w": 104,
    "h": 80
  },
  "st_safari_5": {
    "w": 104,
    "h": 80
  },
  "st_safari_6": {
    "w": 104,
    "h": 80
  },
  "st_safari_7": {
    "w": 104,
    "h": 80
  },
  "st_souk_0": {
    "w": 104,
    "h": 80
  },
  "st_souk_1": {
    "w": 104,
    "h": 80
  },
  "st_souk_2": {
    "w": 104,
    "h": 80
  },
  "st_souk_3": {
    "w": 104,
    "h": 80
  },
  "st_souk_4": {
    "w": 104,
    "h": 80
  },
  "st_souk_5": {
    "w": 104,
    "h": 80
  },
  "st_souk_6": {
    "w": 104,
    "h": 80
  },
  "st_souk_7": {
    "w": 104,
    "h": 80
  },
  "st_tower_0": {
    "w": 104,
    "h": 80
  },
  "st_tower_1": {
    "w": 104,
    "h": 80
  },
  "st_tower_2": {
    "w": 104,
    "h": 80
  },
  "st_tower_3": {
    "w": 104,
    "h": 80
  },
  "st_tower_4": {
    "w": 104,
    "h": 80
  },
  "st_tower_5": {
    "w": 104,
    "h": 80
  },
  "st_tower_6": {
    "w": 104,
    "h": 80
  },
  "st_tower_7": {
    "w": 104,
    "h": 80
  },
  "st_fest_0": {
    "w": 104,
    "h": 80
  },
  "st_fest_1": {
    "w": 104,
    "h": 80
  },
  "st_fest_2": {
    "w": 104,
    "h": 80
  },
  "st_fest_3": {
    "w": 104,
    "h": 80
  },
  "st_fest_4": {
    "w": 104,
    "h": 80
  },
  "st_fest_5": {
    "w": 104,
    "h": 80
  },
  "st_fest_6": {
    "w": 104,
    "h": 80
  },
  "st_fest_7": {
    "w": 104,
    "h": 80
  },
  "ch_packer_0": {
    "w": 66,
    "h": 90
  },
  "ch_packer_1": {
    "w": 66,
    "h": 90
  },
  "ch_packer_2": {
    "w": 66,
    "h": 90
  },
  "ch_cook_0": {
    "w": 66,
    "h": 90
  },
  "ch_cook_1": {
    "w": 66,
    "h": 90
  },
  "ch_cook_2": {
    "w": 66,
    "h": 90
  },
  "ch_creator_0": {
    "w": 66,
    "h": 90
  },
  "ch_creator_1": {
    "w": 66,
    "h": 90
  },
  "ch_creator_2": {
    "w": 66,
    "h": 90
  },
  "ch_engineer_0": {
    "w": 66,
    "h": 90
  },
  "ch_engineer_1": {
    "w": 66,
    "h": 90
  },
  "ch_engineer_2": {
    "w": 66,
    "h": 90
  },
  "ch_taquero_0": {
    "w": 66,
    "h": 90
  },
  "ch_taquero_1": {
    "w": 66,
    "h": 90
  },
  "ch_taquero_2": {
    "w": 66,
    "h": 90
  },
  "ch_bartender_0": {
    "w": 66,
    "h": 90
  },
  "ch_bartender_1": {
    "w": 66,
    "h": 90
  },
  "ch_bartender_2": {
    "w": 66,
    "h": 90
  },
  "ch_sailor_0": {
    "w": 66,
    "h": 90
  },
  "ch_sailor_1": {
    "w": 66,
    "h": 90
  },
  "ch_sailor_2": {
    "w": 66,
    "h": 90
  },
  "ch_broker_0": {
    "w": 66,
    "h": 90
  },
  "ch_broker_1": {
    "w": 66,
    "h": 90
  },
  "ch_broker_2": {
    "w": 66,
    "h": 90
  },
  "ch_tech_0": {
    "w": 66,
    "h": 90
  },
  "ch_tech_1": {
    "w": 66,
    "h": 90
  },
  "ch_tech_2": {
    "w": 66,
    "h": 90
  },
  "ch_mechanic_0": {
    "w": 66,
    "h": 90
  },
  "ch_mechanic_1": {
    "w": 66,
    "h": 90
  },
  "ch_mechanic_2": {
    "w": 66,
    "h": 90
  },
  "ch_butler_0": {
    "w": 66,
    "h": 90
  },
  "ch_butler_1": {
    "w": 66,
    "h": 90
  },
  "ch_butler_2": {
    "w": 66,
    "h": 90
  },
  "ch_guide_0": {
    "w": 66,
    "h": 90
  },
  "ch_guide_1": {
    "w": 66,
    "h": 90
  },
  "ch_guide_2": {
    "w": 66,
    "h": 90
  },
  "ch_goldsmith_0": {
    "w": 66,
    "h": 90
  },
  "ch_goldsmith_1": {
    "w": 66,
    "h": 90
  },
  "ch_goldsmith_2": {
    "w": 66,
    "h": 90
  },
  "ch_builder_0": {
    "w": 66,
    "h": 90
  },
  "ch_builder_1": {
    "w": 66,
    "h": 90
  },
  "ch_builder_2": {
    "w": 66,
    "h": 90
  },
  "ch_vendor_0": {
    "w": 66,
    "h": 90
  },
  "ch_vendor_1": {
    "w": 66,
    "h": 90
  },
  "ch_vendor_2": {
    "w": 66,
    "h": 90
  },
  "street_dropship": {
    "w": 390,
    "h": 280
  },
  "street_restaurant": {
    "w": 390,
    "h": 280
  },
  "street_tiktok": {
    "w": 390,
    "h": 280
  },
  "street_ai": {
    "w": 390,
    "h": 280
  },
  "street_foodtruck": {
    "w": 390,
    "h": 280
  },
  "street_beachclub": {
    "w": 390,
    "h": 280
  },
  "street_yachts": {
    "w": 390,
    "h": 280
  },
  "street_realestate": {
    "w": 390,
    "h": 280
  },
  "street_crypto": {
    "w": 390,
    "h": 280
  },
  "street_supercars": {
    "w": 390,
    "h": 280
  },
  "street_hotel": {
    "w": 390,
    "h": 280
  },
  "street_safari": {
    "w": 390,
    "h": 280
  },
  "street_souk": {
    "w": 390,
    "h": 280
  },
  "street_tower": {
    "w": 390,
    "h": 280
  },
  "street_fest": {
    "w": 390,
    "h": 280
  },
  "ui_office_room": {
    "w": 390,
    "h": 280
  },
  "bld_fest_1": {
    "w": 340,
    "h": 300
  },
  "bld_fest_2": {
    "w": 340,
    "h": 300
  },
  "bld_fest_3": {
    "w": 340,
    "h": 300
  },
  "veh_fest_cart": {
    "w": 74,
    "h": 64
  },
  "veh_fest_cart_rear": {
    "w": 74,
    "h": 64
  },
  "prop_fest_ticketbooth": {
    "w": 86,
    "h": 90
  },
  "mgr_cheer_0": {
    "w": 64,
    "h": 84
  },
  "mgr_cheer_1": {
    "w": 64,
    "h": 84
  },
  "item_fest_ticket": {
    "w": 24,
    "h": 22
  },
  "veh_flatbed_rear": {
    "w": 74,
    "h": 64
  },
  "veh_luggage_rear": {
    "w": 74,
    "h": 64
  },
  "veh_safari_rear": {
    "w": 74,
    "h": 64
  },
  "veh_goldvan_rear": {
    "w": 74,
    "h": 64
  },
  "veh_crane_rear": {
    "w": 74,
    "h": 64
  },
  "veh_order_rear": {
    "w": 74,
    "h": 64
  },
  "veh_supply_rear": {
    "w": 96,
    "h": 64
  },
  "veh_excursion_rear": {
    "w": 74,
    "h": 64
  },
  "bld_dropship_1": {
    "w": 340,
    "h": 300
  },
  "bld_dropship_2": {
    "w": 340,
    "h": 300
  },
  "bld_dropship_3": {
    "w": 340,
    "h": 300
  },
  "bld_restaurant_1": {
    "w": 340,
    "h": 300
  },
  "bld_restaurant_2": {
    "w": 340,
    "h": 300
  },
  "bld_restaurant_3": {
    "w": 340,
    "h": 300
  },
  "bld_tiktok_1": {
    "w": 340,
    "h": 300
  },
  "bld_tiktok_2": {
    "w": 340,
    "h": 300
  },
  "bld_tiktok_3": {
    "w": 340,
    "h": 300
  },
  "bld_ai_1": {
    "w": 340,
    "h": 300
  },
  "bld_ai_2": {
    "w": 340,
    "h": 300
  },
  "bld_ai_3": {
    "w": 340,
    "h": 300
  },
  "bld_foodtruck_1": {
    "w": 340,
    "h": 300
  },
  "bld_foodtruck_2": {
    "w": 340,
    "h": 300
  },
  "bld_foodtruck_3": {
    "w": 340,
    "h": 300
  },
  "bld_beachclub_1": {
    "w": 340,
    "h": 300
  },
  "bld_beachclub_2": {
    "w": 340,
    "h": 300
  },
  "bld_beachclub_3": {
    "w": 340,
    "h": 300
  },
  "bld_yachts_1": {
    "w": 340,
    "h": 300
  },
  "bld_yachts_2": {
    "w": 340,
    "h": 300
  },
  "bld_yachts_3": {
    "w": 340,
    "h": 300
  },
  "bld_realestate_1": {
    "w": 340,
    "h": 300
  },
  "bld_realestate_2": {
    "w": 340,
    "h": 300
  },
  "bld_realestate_3": {
    "w": 340,
    "h": 300
  },
  "bld_crypto_1": {
    "w": 340,
    "h": 300
  },
  "bld_crypto_2": {
    "w": 340,
    "h": 300
  },
  "bld_crypto_3": {
    "w": 340,
    "h": 300
  },
  "bld_supercars_1": {
    "w": 340,
    "h": 300
  },
  "bld_supercars_2": {
    "w": 340,
    "h": 300
  },
  "bld_supercars_3": {
    "w": 340,
    "h": 300
  },
  "bld_hotel_1": {
    "w": 340,
    "h": 300
  },
  "bld_hotel_2": {
    "w": 340,
    "h": 300
  },
  "bld_hotel_3": {
    "w": 340,
    "h": 300
  },
  "bld_safari_1": {
    "w": 340,
    "h": 300
  },
  "bld_safari_2": {
    "w": 340,
    "h": 300
  },
  "bld_safari_3": {
    "w": 340,
    "h": 300
  },
  "bld_souk_1": {
    "w": 340,
    "h": 300
  },
  "bld_souk_2": {
    "w": 340,
    "h": 300
  },
  "bld_souk_3": {
    "w": 340,
    "h": 300
  },
  "bld_tower_1": {
    "w": 340,
    "h": 300
  },
  "bld_tower_2": {
    "w": 340,
    "h": 300
  },
  "bld_tower_3": {
    "w": 340,
    "h": 300
  }
};
