"""Register final world/decoration/high-rank sheets. No source pixels are repainted.
Optional editor requirements: Pillow, NumPy, SciPy. Shipped files work without Python.
"""
from pathlib import Path
from PIL import Image
from scipy import ndimage
import numpy as np
import json
root=Path(__file__).resolve().parents[1];out=root/'public/sprites/generated'
biz=['dropship','restaurant','tiktok','ai','foodtruck','beachclub','yachts','realestate','crypto','supercars','hotel','safari','souk','tower']
families={
 'business-decor':(7,[0,237,474,711,948],[f'decor_{b}_{tier}' for tier in [2,3] for b in biz]),
 'world-details':(4,[0,316,615,841,1024],['veh_order','ch_critic_0','prop_broadcast','prop_research','tree_0','tree_1','palm','bush','bench','lamp_post','recycling_bin','desert_palm','tile_madrid_ground','tile_miami_ground','tile_dubai_ground','tile_path']),
 'stations-premium':(7,[0,325,566,805,1061],[f'st_{b}_r{rank}' for rank in [4,5] for b in biz]),
}
frames={};sheets=[]
for file,(cols,ys,keys) in families.items():
 im=Image.open(out/(file+'.png'));sheet='generated-'+file;atlas={};sheets.append({'key':sheet,'file':file})
 for i,key in enumerate(keys):
  col,row=i%cols,i//cols;x0=round(col*im.width/cols);x1=round((col+1)*im.width/cols);y0,y1=ys[row:row+2]
  mask=np.asarray(im.getchannel('A').crop((x0,y0,x1,y1)))>24
  labels,n=ndimage.label(ndimage.binary_dilation(mask,iterations=2));counts=np.bincount(labels.ravel());counts[0]=0
  yy,xx=np.where(labels==counts.argmax());x=max(x0,x0+int(xx.min())-2);y=max(y0,y0+int(yy.min())-2);w=min(x1,x0+int(xx.max())+3)-x;h=min(y1,y0+int(yy.max())+3)-y
  frames[key]={'sheet':sheet,'file':file,'x':x,'y':y,'w':w,'h':h,'sheetW':im.width,'sheetH':im.height}
  atlas[key]={'frame':{'x':x,'y':y,'w':w,'h':h},'rotated':False,'trimmed':False,'spriteSourceSize':{'x':0,'y':0,'w':w,'h':h},'sourceSize':{'w':w,'h':h}}
 if file=='stations-premium':
  for rank in [4,5]:
   key=f'wh_shelf_r{rank}';frames[key]=dict(frames[f'st_dropship_r{rank}']);atlas[key]=dict(atlas[f'st_dropship_r{rank}'])
 (out/(file+'.json')).write_text(json.dumps({'frames':atlas,'meta':{'image':file+'.png','size':{'w':im.width,'h':im.height},'scale':'1'}},indent=2)+'\n')
(root/'src/art/completionFrames.ts').write_text('/** Generated by scripts/register-completion-atlases.py. */\nexport const COMPLETION_SHEETS = '+json.dumps(sheets,indent=2)+' as const;\nexport const COMPLETION_FRAMES = '+json.dumps(frames,indent=2)+';\n')
print(f'Registered {len(frames)} final art frames')
