"""Register authored atlas cells without repainting source pixels. Requires Pillow.
Run after replacing source sheets; the shipped JSON/TS are sufficient at runtime.
"""
from pathlib import Path
import json
from PIL import Image
import numpy as np
from scipy import ndimage

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'public/sprites/generated'
FAMILIES = {
 'vehicles': (4, [0,443,887], ['veh_safari','veh_crane','veh_luggage','veh_flatbed','veh_goldvan','car_miami_0','car_miami_1','dubai_lamp']),
 'dubai-buildings': (5, [0, 312, 655, 1024], [f'bld_{b}_{t}' for t in [1,2,3] for b in ['supercars','hotel','safari','souk','tower']]),
 'avatars': (4, [0,512,1024], ['avatar_'+b for b in ['tracksuit','hoodie','suit','designer','goldtux','neonsuit','vampire','founder']]),
 'dubai-details': (4, [0,295,565,808,1086], ['st_supercars','st_hotel','st_safari','st_souk','st_tower','item_carkey','item_bell','item_camel','item_ring','item_beam','ch_mechanic_0','ch_valet_0','ch_butler_0','ch_guide_0','ch_goldsmith_0','ch_builder_0']),
 'luxury': (5, [0,267,515,754,1024], ['lux_'+b for b in ['digital','luxwatch','goldchain','diamondring','crown','deliverybike','scooter','motorbike','sportscar','supercar','limo','goldcar','parents','flat','penthouse','villa','mansion','island','hearse','haunted']]),
 'lifestyle-extras': (4, [0,315,626,935,1254], ['lux_'+b for b in ['cat','dog','parrot','tiger','penguin','pumpkin','yacht','jet','rocket','vampire','skullring']]+['ghost','veh_supply','ch_vip_0','dubai_planter','miami_plaza']),
}
frames = {}
sheets = []
for file, (cols, rows, keys) in FAMILIES.items():
 im = Image.open(OUT / (file+'.png')).convert('RGBA')
 # The extra sheet is square. Keep fractional cell edges deterministic.
 xs = [round(i * im.width / cols) for i in range(cols+1)]
 if file == 'dubai-details': xs = [0,374,734,1117,1448]
 if rows[-1] != im.height: raise ValueError((file, im.size, rows))
 sheet = 'generated-'+file
 sheets.append({'key':sheet,'file':file})
 atlas = {}
 for index, key in enumerate(keys):
  c, r = index % cols, index // cols
  x0,y0,x1,y1 = xs[c],rows[r],xs[c+1],rows[r+1]
  alpha = im.getchannel('A').crop((x0,y0,x1,y1)).point(lambda a:255 if a>8 else 0)
  # Reject detached fragments from the adjacent row without changing any source pixel.
  mask = np.asarray(alpha) > 0
  labels, count = ndimage.label(ndimage.binary_dilation(mask, iterations=2))
  counts = np.bincount(labels.ravel()); counts[0] = 0
  selected = labels == counts.argmax()
  yy, xx = np.where(selected)
  box = (int(xx.min()),int(yy.min()),int(xx.max())+1,int(yy.max())+1) if count else None
  if not box: raise ValueError(key+' is empty')
  l,t,rr,bb=box
  # 2 pixel gutters preserve antialiasing; no scale or edits to the sheet.
  x,y=max(x0,x0+l-2),max(y0,y0+t-2)
  w,h=min(x1,x0+rr+2)-x,min(y1,y0+bb+2)-y
  if file == 'avatars':
   x,y,w,h=x0+22,y0+4,340,504
  frames[key]={'sheet':sheet,'file':file,'x':x,'y':y,'w':w,'h':h,'sheetW':im.width,'sheetH':im.height}
  atlas[key]={'frame':{'x':x,'y':y,'w':w,'h':h},'rotated':False,'trimmed':False,'spriteSourceSize':{'x':0,'y':0,'w':w,'h':h},'sourceSize':{'w':w,'h':h}}
 # Shared frames are references, not copied pixel data.
 for key in list(atlas):
  aliases=[]
  if key.startswith('avatar_') and key != 'avatar_vampire' and key != 'avatar_founder': aliases.append('lux_'+key[7:])
  if key.startswith('lux_') and key[4:] in ['deliverybike','scooter','motorbike','sportscar','supercar','limo','goldcar','hearse']: aliases.append('luxcar_'+key[4:])
  if key=='lux_pumpkin': aliases.append('pumpkin')
  if key=='dubai_planter': aliases += ['decor_'+b+'_'+str(t) for b in ['supercars','hotel','safari','souk','tower'] for t in [2,3]]
  if key=='miami_plaza': aliases += ['decor_'+b+'_'+str(t) for b in ['foodtruck','beachclub','yachts','realestate','crypto'] for t in [2,3]]
  for alias in aliases: frames[alias]=dict(frames[key]);atlas[alias]=dict(atlas[key])
 if file=='avatars':
  f=dict(frames['avatar_founder']);f.update(y=f['y'],h=round(f['h']*.47))
  frames['exec_founder']=f
  atlas['exec_founder']={'frame':{k:f[k] for k in ['x','y','w','h']},'rotated':False,'trimmed':False,'spriteSourceSize':{'x':0,'y':0,'w':f['w'],'h':f['h']},'sourceSize':{'w':f['w'],'h':f['h']}}
 (OUT/(file+'.json')).write_text(json.dumps({'frames':atlas,'meta':{'image':file+'.png','size':{'w':im.width,'h':im.height},'scale':'1'}},indent=2)+'\n')
(ROOT/'src/art/visualFrames.ts').write_text('/** Original visual completion atlases. Generated by scripts/register-visual-atlases.py. */\nexport const VISUAL_SHEETS = '+json.dumps(sheets,indent=2)+' as const;\nexport const VISUAL_FRAMES: Record<string, { sheet: string; file: string; x: number; y: number; w: number; h: number; sheetW: number; sheetH: number }> = '+json.dumps(frames,indent=2)+';\n')
print(f'Registered {len(frames)} frames across {len(sheets)} shared sources')
